### ISSUE TITLE
Namespaces doubling up in current launch files

### ISSUE THREAD

**Issue by bobbleballs** [NVIDIA-ISAAC-ROS/isaac_ros_mission_client#2]
Hi,
There is a bug in the current launch files for the Mission Client when using namespaces.
When launching the client with a namespace argument e.g 
`~/projects/isaac_mission$ ros2 launch isaac_ros_vda5050_nav2_client_bringup isaac_ros_vda5050_client.launch.py ros_namespace:='r0'
` 
The nodes that are launched appear to heave their namespace applied twice.
`[INFO] [vda5050_nav2_client-1]: process started with pid [208488]
[INFO] [ros_to_mqtt_bridge_node-2]: process started with pid [208490]
[INFO] [mqtt_to_ros_bridge_node-3]: process started with pid [208492]
[mqtt_to_ros_bridge_node-3] [INFO] [1674476648.202187545] [`**r0.r0**`.mqtt_ros_bridge_node]: Connected with result code 0
[ros_to_mqtt_bridge_node-2] [INFO] [1674476648.212896233] [`**r0.r0**`.ros_mqtt_bridge_node]: Connected with result code 0
`
It appears that `ros_namespace` is a built in parameter for the ros_launch system. And that by using that name as the parameter the namespace gets applied twice.

Simply changing the parameter name fixes this issue - Below I have changed the ros_namespace parameter to be called `namespace` and it works fine:

`~/projects/isaac_mission/src/isaac_ros_mission_client$ ros2 launch isaac_ros_vda5050_nav2_client_bringup isaac_ros_vda5050_client.launch.py namespace:='r0'
[INFO] [vda5050_nav2_client-1]: process started with pid [213704]
[INFO] [ros_to_mqtt_bridge_node-2]: process started with pid [213706]
[INFO] [mqtt_to_ros_bridge_node-3]: process started with pid [213708]
[mqtt_to_ros_bridge_node-3] [INFO] [1674477353.721697169] [r0.mqtt_ros_bridge_node]: Connected with result code 0
[ros_to_mqtt_bridge_node-2] [INFO] [1674477353.739631580] [r0.ros_mqtt_bridge_node]: Connected with result code 0
`
Cheers,
Ben

**Comment by bobbleballs** [comment]
Also the Nav2 client launch file does not pass the namespace to the mission client. I am not using this one but I noticed it whilst looking into this.

**Comment by hemalshahNV** [comment]
Thanks for pointing this out! We'll have this fixed shortly in the launch file.

**Comment by jaiveersinghNV** [comment]
Thanks @bobbleballs - we've just merged a PR that updates the namespace parameter across our various launch files. Hopefully that should fix your issue!

https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_mission_client/pull/3

**Comment by bobbleballs** [comment]
New namespaces look good to me, thanks.
The [Nav2 launch file](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_mission_client/blob/1bf123dcb6b173b192e7fbb037c560c95b46a241/isaac_ros_vda5050_nav2_client_bringup/launch/isaac_ros_vda5050_nav2_client.launch.py#L143) still doesn't pass them through to the client bringup however. 

Probably should look something like this:

`    mission_client_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([mission_client_launch_dir,
                                       '/isaac_ros_vda5050_client.launch.py']),
    launch_arguments={
            'namespace': namespace}
    )`

Not sure if this is a separate issue though?
Thanks for getting on it!

Cheers,
Ben

**Comment by jaiveersinghNV** [comment]
Ah, you're right - we'll get another hotfix out for that shortly. Appreciate the careful eye!

**Comment by jaiveersinghNV** [comment]
We've just merged #5 which properly forwards the `namespace` parameter. Thanks for reporting these issues! We've re-verified all the launch files on our end, but if you run into any other problems, please open a new issue and we'll jump on it ASAP

**Comment by bobbleballs** [comment]
Lgtm!
